import play.sbt.routes.RoutesKeys
import sbt.Def
import scoverage.ScoverageKeys

ThisBuild / scalaVersion := "3.7.4"

lazy val appName: String = "soft-drinks-industry-levy-variations-frontend"

lazy val root = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin) //Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(inConfig(Test)(testSettings): _*)
  .settings(majorVersion := 0, libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always) // libraryDependencySchemes added to get around the scoverage compile errors for scala 2.13.10
  .settings(ThisBuild / useSuperShell := false)
  .settings(
    name := appName,
    RoutesKeys.routesImport ++= Seq(
      "models._",
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl"
    ),
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.HtmlFormat",
      "play.twirl.api.HtmlFormat._",
      "uk.gov.hmrc.govukfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.helpers._",
      "uk.gov.hmrc.hmrcfrontend.views.config._",
      "views.ViewUtils._",
      "models.Mode",
      "controllers.routes._",
      "viewmodels.govuk.all._"
    ),
    PlayKeys.playDefaultPort := 8705,
    ScoverageKeys.coverageExcludedFiles := "<empty>;Reverse.*;.*handlers.*;.*components.*;" +
      ".*Routes.*;.*viewmodels.govuk.*;.*models.*;",
    ScoverageKeys.coverageMinimumStmtTotal := 87,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true,
    scalacOptions += "-deprecation",
    scalacOptions ++= Seq(
      "-feature",
      "-Wconf:cat=deprecation:s,cat=feature:s,src=target/.*:s,msg=Flag.*repeatedly:s,msg=unused explicit parameter*:s,msg=unused local definition*:s"
    ),
    libraryDependencies ++= AppDependencies.all,
    retrieveManaged := true,
    // concatenate js
    Concat.groups := Seq(
      "javascripts/application.js" ->
        group(Seq(
          "javascripts/app.js"
        ))
    ),
    // scalacOptions += "-deprecation",
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    pipelineStages := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat,uglify),
    // only compress files generated by concat
    uglify / includeFilter := GlobFilter("application.js")
  )
  .settings(majorVersion := 0, libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always)

lazy val testSettings: Seq[Def.Setting[_]] = Seq(
  fork := true,
  javaOptions += "-XX:+EnableDynamicAgentLoading",
  unmanagedSourceDirectories += baseDirectory.value / "test-utils"
)

lazy val it = (project in file("it"))
  .enablePlugins(PlayScala)
  .disablePlugins(SbtDistributablesPlugin)
  .dependsOn(root % "test->test")
  .settings(
    majorVersion := 0,
    Test / unmanagedSourceDirectories := Seq(baseDirectory.value),
    Test / unmanagedResourceDirectories := Seq(baseDirectory.value / "resources"),
    Test / parallelExecution := false,
    Test / fork := true,
    Test / javaOptions += "-XX:+EnableDynamicAgentLoading",
      scalacOptions += "-Wconf:msg=Flag.*repeatedly:s"
  )
